version: "3.9"

services:
  db:
    image: mysql:8
    container_name: jobs-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mock-external:
    build: ./mock_service
    container_name: mock-external
    ports:
      - "8081:8081"

  # Candidate service
  # job-server:
  #   build: ./job-server
  #   depends_on:
  #     - db
  #     - mock-external
  #   ports:
  #     - "8080:8080"

volumes:
  db_data:

