version: "3.9"

services:
  mysql-db:
    image: mysql:8
    container_name: jobs-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot" ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s

  mock-external:
    build: ./mock_service
    container_name: mock-external
    ports:
      - "8081:8081"

  job-server:
    build:
      context: ./job-server
      dockerfile: src/main/resources/Dockerfile
    depends_on:
      mysql-db:
        condition: service_healthy
      mock-external:
        condition: service_started
    environment:
      EXTERNAL_MOCK_SERVICE: mock-external
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      DB_NAME: jobs
      MYSQL_USER: root
      MYSQL_PWD: root
    ports:
      - "8080:8080"


volumes:
  db_data:

