spring:
  application:
    name: job-server

  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_NAME:jobs}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:root}
    pool:
      enabled: true
      max-size: 10
      initial-size: 3
      max-idle-time: 30m
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

external:
  service:
    job:
      base-url: http://${EXTERNAL_MOCK_SERVICE:localhost}:8081
      timeout:
        connect: 3s #TCP connection timeout
        response: 10s #total time to first response
        read: 10s #read/write - data transfer
        write: 10s

resilience4j:
  retry:
    instances:
      externalService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - io.netty.channel.ConnectTimeoutException
          - io.netty.handler.timeout.ReadTimeoutException
  circuitbreaker:
    instances:
      externalService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: job-server

server:
  port: 8080

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.retry.internal: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

